#! /usr/bin/python3

import sys
import random

args = list(' '.join(sys.argv[1:]))

if len(args) == 0:
    args = list(sys.stdin.read())
    del args[-1]

for i, letter in enumerate(args):
    if random.choice([True, False]):
        args[i] = args[i].upper()
    else:
        args[i] = args[i].lower()

print(''.join(args))
